# This workflow will build and deploy the MkDocs site to GitHub Pages
# Save this file as .github/workflows/gh-pages.yml in your repository

name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies with Pipenv
        run: |
          cd src
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      - name: Build MkDocs site
        run: |
          cd src
          pipenv run mkdocs build --strict

      - name: Deploy to GitHub Pages with mkdocs
        run: |
          cd src
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          pipenv run mkdocs gh-deploy --force --remote-name origin --remote-branch gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
